#!/usr/bin/env bash
# Review-before-merge agent for the Feedback Pipe.
#
# WHY THIS EXISTS. Feedback arrives from untrusted end users and is handed
# verbatim to a coding agent. Letting that agent edit a live checkout (or push
# to a default branch) means a hostile message could ship code unreviewed. This
# wrapper makes the agent's output REVIEWABLE by construction: every task runs
# on its own throwaway branch and lands as a pull request a human approves.
# Nothing reaches the default branch without that review.
#
# Use it by pointing the pipe at this script:
#   PIPE_AGENT_COMMAND='/absolute/path/to/examples/agents/review-agent.sh'
#
# The pipe passes these in the environment (see README):
#   APE_TASK_PROMPT_FILE  the feedback, verbatim, as a prompt
#   APE_TASK_ID           the task id (used to name the branch)
#   APE_REPO_PATH         the repository the agent works on
#
# Auth: the coding agent inherits this process's environment, so `claude login`
# (OAuth / subscription) on this host is enough — no API key needs to live in
# the pipe. Set ANTHROPIC_API_KEY instead if you prefer key auth.
set -euo pipefail

repo="${APE_REPO_PATH:?APE_REPO_PATH is required}"
task_id="${APE_TASK_ID:-$(date +%s)}"
prompt_file="${APE_TASK_PROMPT_FILE:?APE_TASK_PROMPT_FILE is required}"

# The coding agent to run. Overridable (Codex, Aider, …) and, for tests, a stub.
# Default: Claude Code headless, auto-accepting edits WITHIN this branch only.
coding_agent="${PIPE_CODING_AGENT:-claude -p "\$(cat \"\$APE_TASK_PROMPT_FILE\")" --permission-mode acceptEdits}"

# Where PRs target. Defaults to the repo's current default branch.
base_branch="${PIPE_BASE_BRANCH:-$(git -C "$repo" symbolic-ref --quiet --short HEAD 2>/dev/null || echo main)}"
branch="feedback/${task_id}"

log() { echo "[review-agent ${task_id}] $*"; }

cd "$repo"

# Start from a clean, up-to-date base branch. Runs are serialized by the pipe
# (one working tree, one writer), so branch switching here is safe.
git fetch --quiet origin "$base_branch" 2>/dev/null || true
git checkout --quiet "$base_branch"
git merge --quiet --ff-only "origin/${base_branch}" 2>/dev/null || true
git checkout --quiet -B "$branch"

log "running coding agent on branch ${branch}"
# eval so PIPE_CODING_AGENT can carry flags/quotes; it is operator-controlled.
eval "$coding_agent"

# Stage everything the agent produced, minus the pipe's own task scratch (.ape/
# is gitignored already, but be explicit).
git add --all -- ':!.ape'

if git diff --cached --quiet; then
  log "agent made no changes; nothing to review"
  git checkout --quiet "$base_branch"
  git branch --quiet -D "$branch" 2>/dev/null || true
  exit 0
fi

git commit --quiet -m "Feedback ${task_id}: agent-proposed change

Generated by the Feedback Pipe review agent from user feedback.
Review before merging — the source is untrusted end-user input."

if git push --quiet -u origin "$branch" 2>/dev/null; then
  log "pushed ${branch}"
  if command -v gh >/dev/null 2>&1; then
    gh pr create --draft --base "$base_branch" --head "$branch" \
      --title "Feedback ${task_id}: agent-proposed change" \
      --body "Automated change from user feedback via the Feedback Pipe. **Review before merging — the source is untrusted end-user input.**" \
      && log "opened draft PR" || log "push succeeded; open a PR for ${branch} manually"
  else
    log "push succeeded; open a PR for ${branch} (gh not installed)"
  fi
else
  log "could not push ${branch}; the change is committed locally for review"
fi

# Leave the repo back on its base branch, ready for the next task.
git checkout --quiet "$base_branch"
